Repository PETSTIVAL/frontend, pull requests merged in 2024-10, with the labels that each got.

#8 docs: Github PR, Issue Template 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 chore: 모바일 퍼스트 CSS 및 Page Router 작성 #14 close
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/index.css
  src/pages/LoginPage.jsx
  src/routes/AppPages.jsx
  src/routes/RouteDef.jsx
Labels: enhancement

#24 feat: 소셜 로그인 기능 추가완료 #17 close
  package-lock.json
  package.json
  src/App.css
  src/assets/images/login-button/facebook.svg
  src/assets/images/login-button/google.svg
  src/assets/images/login-button/kakaotalk.svg
  src/assets/logo/logo-wrapper.svg
  src/components/login/FacebookLoginButton.jsx
  src/components/login/GoogleLoginButton.jsx
  src/components/login/KakaoLoginButton.jsx
  src/components/login/LoginButtons.css
  src/hooks/useLogin.js
  src/index.css
  src/pages/LoginPage.jsx
  src/pages/login/Login.css
  src/pages/login/LoginPage.jsx
  src/routes/RouteDef.jsx
Labels: enhancement

#38 feat: 반려견 프로필 페이지 및 프로필 업로드 기능 구현 완료
  package-lock.json
  package.json
  src/App.css
  src/assets/icons/angle-left.svg
  src/assets/icons/camera.svg
  src/assets/icons/profile-pet.svg
  src/components/Common/Button/Button.jsx
  src/components/Common/Button/Button.module.css
  src/components/Common/Input/Input.jsx
  src/components/Common/Input/Input.module.css
  src/components/PetProfile/ProfileSurvey.jsx
  src/components/PetProfile/ProfileSurvey.module.css
  src/components/PetProfile/RadioButton.jsx
  src/components/PetProfile/RadioButton.module.css
  src/components/PetProfile/RadioGroup.jsx
  src/components/PetProfile/RadioGroup.module.css
  src/components/PetProfile/UploadProfileButton.jsx
  src/components/PetProfile/UploadProfileButton.module.css
  src/hooks/useLogin.js
  src/hooks/usePetProfileSurvey.js
  src/index.css
  src/pages/PaymentsPage/CheckoutPage.jsx
  src/pages/PetProfileSurveyPage/PetProfileSurveyPage.jsx
  src/pages/PetProfileSurveyPage/PetProfileSurveyPage.module.css
  src/routes/RouteDef.jsx
  src/service/postPetProfile.js
  src/service/supabaseClient.js
  src/service/uploadProfileImg.js
  vite.config.js
Labels: enhancement

#41 docs: README.md 수정
  README.md
Labels: documentation

#48 feat: 반려견 페이지, 반려견 상세정보 페이지 구현 완료 #42 close
  src/assets/icons/plus.svg
  src/components/PaymentsPage/OrderInfo.jsx
  src/components/Pet/PetProfileCard.jsx
  src/components/Pet/PetProfileCard.module.css
  src/components/PetProfileSurvey/ProfileSurvey.jsx
  src/components/PetProfileSurvey/ProfileSurvey.module.css
  src/components/PetProfileSurvey/RadioButton.jsx
  src/components/PetProfileSurvey/RadioButton.module.css
  src/components/PetProfileSurvey/RadioGroup.jsx
  src/components/PetProfileSurvey/RadioGroup.module.css
  src/components/PetProfileSurvey/UploadProfileButton.jsx
  src/components/PetProfileSurvey/UploadProfileButton.module.css
  src/hooks/useLogin.js
  src/pages/PaymentsPage/CheckoutPage.jsx
  src/pages/PetPage/PetPage.jsx
  src/pages/PetPage/PetPage.module.css
  src/pages/PetPage/PetProfilePage/PetProfilePage.jsx
  src/pages/PetPage/PetProfilePage/PetProfilePage.module.css
  src/pages/PetProfileSurveyPage/PetProfileSurveyPage.jsx
  src/routes/RouteDef.jsx
  src/services/fetchPetProfile.js
  src/services/insertPetProfile.js
  src/services/supabaseClient.js
  src/services/uploadProfileImg.js
  src/stores/useTotalStore.jsx
  src/stories/DetailBar.jsx
Labels: enhancement

#53 feat: 로그아웃 회원탈퇴 기능
  package-lock 2.json
  package-lock.json
  package.json
  src/components/Mypage/MyAccount.jsx
  src/components/Mypage/MyProfile.jsx
  src/components/login/FacebookLoginButton.jsx
  src/components/login/GoogleLoginButton.jsx
  src/components/login/KakaoLoginButton.jsx
  src/hooks/useAuth.js
  src/hooks/useLogin.js
  src/pages/Oauth/OauthPage.jsx
  src/pages/PetstivalListPage/PetstivalListPage.jsx
  src/services/supabaseAdminClient.js
  src/stores/useAuthStore.jsx
Labels: enhancement

#56 feat: 반려견 프로필 생성 및 수정 시 유효성 검사 기능 추가 #49 close
  src/components/Common/Button/Button.jsx
  src/components/Common/Input/Input.jsx
  src/components/Common/Input/Input.module.css
  src/components/Common/Input/InputNumber.jsx
  src/components/Common/Input/InputNumber.module.css
  src/components/Pet/PetProfileCard.jsx
  src/components/PetProfileSurvey/ProfileSurvey.jsx
  src/components/PetProfileSurvey/UploadProfileButton.jsx
  src/hooks/usePetProfileSurvey.js
  src/pages/PetPage/EditPetProfilePage/EditPetProfilePage.jsx
  src/pages/PetPage/EditPetProfilePage/EditPetProfilePage.module.css
  src/pages/PetPage/PetPage.jsx
  src/pages/PetPage/PetProfilePage/PetProfilePage.jsx
  src/pages/PetProfileSurveyPage/PetProfileSurveyPage.jsx
  src/routes/RouteDef.jsx
  src/services/fetchPetProfile.js
  src/services/insertPetProfile.js
  src/services/updatePetProfile.js
  src/services/uploadProfileImg.js
  src/utils/getDateToday.js
Labels: enhancement

#67 fix: 반려견 관련 페이지 수정
  src/assets/icons/profile-pet-gray.svg
  src/components/Common/Input/Input.jsx
  src/components/Pet/NoPetsCard.jsx
  src/components/Pet/PetProfileCard.jsx
  src/components/PetProfileSurvey/ProfileSurvey.jsx
  src/components/PetProfileSurvey/UploadProfileButton.jsx
  src/hooks/usePetProfileSurvey.js
  src/pages/PetPage/EditPetProfilePage/EditPetProfilePage.jsx
  src/pages/PetPage/PetPage.jsx
  src/pages/PetPage/PetPage.module.css
  src/pages/PetPage/PetProfilePage/PetProfilePage.jsx
  src/pages/PetPage/PetProfilePage/PetProfilePage.module.css
  src/pages/PetProfileSurveyPage/PetProfileSurveyPage.jsx
  src/routes/RouteDef.jsx
  src/services/fetchPetProfile.js
  src/services/insertPetProfile.js
  src/services/updatePetProfile.js
  src/services/uploadProfileImg.js
Labels: bug

#73 feat: 반려견 프로필 삭제 기능 구현 #68 close
  src/assets/icons/cancel.svg
  src/components/Pet/PetProfileCard.jsx
  src/components/Pet/PetProfileDetailCard.jsx
  src/components/Pet/PetProfileDetailCard.module.css
  src/hooks/usePetProfileSurvey.js
  src/pages/PetPage/EditPetProfilePage/EditPetProfilePage.jsx
  src/pages/PetPage/EditPetProfilePage/EditPetProfilePage.module.css
  src/pages/PetPage/PetPage.module.css
  src/pages/PetPage/PetProfilePage/PetProfilePage.jsx
  src/services/deletePetProfile.js
  src/utils/formatDate.js
  vite.config.js
Labels: enhancement

#78 feat: OAuth 페이지 최초 로그인 분기 추가 및 alert를 모달로 변경 #76 close
  src/components/Mypage/MyAccount.jsx
  src/components/PetProfileSurvey/ProfileSurvey.jsx
  src/hooks/usePetProfileSurvey.js
  src/pages/Oauth/OauthPage.jsx
  src/pages/Oauth/OauthPage.module.css
  src/pages/PetPage/EditPetProfilePage/EditPetProfilePage.jsx
  src/pages/PetPage/PetProfilePage/PetProfilePage.jsx
Labels: enhancement
